Repository vmware/dispatch, pull requests merged in 2018-07, with the labels that each got.

#550 Create API paths under org name
  docs/_guides/quickstart.md
  e2e/tests/apis.bats
  e2e/tests/organizations.bats
  e2e/tests/variables.bash
  pkg/api-manager/controller.go
  pkg/api-manager/handlers.go
  pkg/api-manager/handlers_test.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/create_api.go
  pkg/event-sidecar/cmd.go
Labels: cla-not-required, run-e2e

#552 release 0.1.20
  CHANGELOG.md
  docs/_posts/2018-07-03-v0-1-20-release.md
  docs/_usage/functions.md
Labels: cla-not-required, run-e2e

#553 Add e2e tests to release pipeline
  ci/pipelines/release.yml
Labels: cla-not-required

#556 Add local API gateway to API manager
  e2e/tests/apis.bats
  e2e/tests/helpers.bash
  pkg/api-manager/controller.go
  pkg/api-manager/controller_test.go
  pkg/api-manager/gateway/local/gateway.go
  pkg/api-manager/gateway/local/gateway_test.go
  pkg/api-manager/gateway/local/router.go
  pkg/api-manager/gateway/local/router_test.go
  pkg/client/errors.go
  pkg/dispatchserver/apis.go
  pkg/dispatchserver/config.go
  pkg/dispatchserver/events.go
  pkg/dispatchserver/images.go
  pkg/dispatchserver/local.go
  pkg/dispatchserver/local_test.go
  pkg/dispatchserver/main.go
  pkg/http/crypto.go
  pkg/http/crypto_test.go
  pkg/http/handlers.go
  pkg/http/handlers_test.go
  pkg/http/server.go
Labels: run-e2e

#559 Remove built-in event driver
  Makefile
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/event-manager/values.yaml
  ci/pipelines/e2e.yml
  cmd/event-driver/main.go
  cmd/event-manager/main.go
  images/event-driver/Dockerfile
  pkg/api/v1/event_driver_type.go
  pkg/dispatchcli/cmd/create_eventdriver.go
  pkg/dispatchcli/cmd/get_eventdrivertype.go
  pkg/entity-store/libkv.go
  pkg/entity-store/store.go
  pkg/entity-store/store_test.go
  pkg/event-driver/cmd/cmd.go
  pkg/event-driver/cmd/vcenter.go
  pkg/event-driver/cmd/vcenter_test.go
  pkg/event-driver/driver.go
  pkg/event-driver/drivers/vcenter/handlers.go
  pkg/event-driver/drivers/vcenter/vcenter.go
  pkg/event-driver/types.go
  pkg/event-manager/drivers/entities/driver_type.go
  pkg/event-manager/drivers/http_handlers.go
  pkg/event-manager/drivers/http_handlers_test.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/handlers.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#561 Add Org to bulk create CLI
  pkg/dispatchcli/cmd/create.go
Labels: cla-not-required

#560 Helm chart enhancements
  charts/dispatch/charts/api-manager/templates/deployment.yaml
  charts/dispatch/charts/application-manager/templates/deployment.yaml
  charts/dispatch/charts/echo-server/templates/deployment.yaml
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/function-manager/templates/deployment.yaml
  charts/dispatch/charts/function-manager/values.yaml
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  charts/dispatch/charts/identity-manager/templates/ingress.noauth.yaml
  charts/dispatch/charts/image-manager/templates/deployment.yaml
  charts/dispatch/charts/image-manager/values.yaml
  charts/dispatch/charts/secret-store/templates/deployment.yaml
  charts/dispatch/charts/service-manager/templates/deployment.yaml
  charts/dispatch/templates/_helpers.tpl
  charts/dispatch/values.yaml
  pkg/dispatchcli/cmd/install_config.go
Labels: cla-not-required, run-e2e

#566 Include dispatch-server in the release
  CHANGELOG.md
  ci/pipelines/release.yml
  ci/release/binaries.yml
  ci/release/release-images.yml
Labels: run-e2e

#567 v0.1.21 RELEASE
  CHANGELOG.md
  docs/_posts/2018-07-10-v0-1-21-release.md
Labels: cla-not-required, run-e2e

#568 Fix minor issues in release pipeline
  ci/pipelines/release.yml
Labels: cla-not-required

#569 Fix dispatch uninstall cmd ignoring config file
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/runner.go
  pkg/dispatchcli/cmd/uninstall.go
  pkg/dispatchcli/cmd/uninstall_test.go
Labels: cla-not-required, run-e2e

#570 Bump version of PhotonOS in our images
  images/dispatch-server/Dockerfile
  images/event-sidecar/Dockerfile
Labels: cla-not-required, run-e2e

#563 Add bash completion script
  scripts/dispatch_bash_completion.sh
Labels: cla-not-required

#551 Add CI base images pipeline
  ci/README.md
  ci/base-images/base-image-tag.yml
  ci/base-images/config-dispatch-env.sh
  ci/base-images/config-gke-env.sh
  ci/base-images/config-k8s-env.sh
  ci/base-images/configs/dispatch-config.json
  ci/base-images/configs/dispatch-install.yml
  ci/base-images/gke-cluster-create.yml
  ci/base-images/gke-cluster-delete.yml
  ci/base-images/install-dispatch.yml
  ci/base-images/tests/clojure/task.yml
  ci/base-images/tests/clojure/tests.bats
  ci/base-images/tests/java/task.yml
  ci/base-images/tests/java/tests.bats
  ci/base-images/tests/nodejs/task.yml
  ci/base-images/tests/nodejs/tests.bats
  ci/base-images/tests/powershell/task.yml
  ci/base-images/tests/powershell/tests.bats
  ci/base-images/tests/python3/task.yml
  ci/base-images/tests/python3/tests.bats
  ci/base-images/tests/run-tests.sh
  ci/base-images/uninstall-dispatch.yml
  ci/pipelines/base-images.yml
Labels: cla-not-required

#572 [CI base images] Fix tests and report pr status
  ci/base-images/tests/clojure/task.yml
  ci/base-images/tests/java/task.yml
  ci/base-images/tests/java/tests.bats
  ci/base-images/tests/nodejs/task.yml
  ci/base-images/tests/nodejs/tests.bats
  ci/base-images/tests/powershell/task.yml
  ci/base-images/tests/python3/task.yml
  ci/base-images/tests/run-tests.sh
  ci/pipelines/base-images.yml
Labels: cla-not-required

#548 Move source out of function entity and into its own entity store
  pkg/api/v1/function.go
  pkg/function-manager/controller.go
  pkg/function-manager/controller_test.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/function-manager/handlers_test.go
  pkg/functions/builder.go
  pkg/functions/builder_test.go
  pkg/functions/entities.go
  pkg/functions/mocks/image_builder.go
  pkg/functions/types.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#577 v0.1.22 RELEASE
  CHANGELOG.md
  docs/_posts/2018-07-18-v0-1-22-release.md
Labels: cla-not-required

#579 Clean up leaked images and FaaS deployments
  e2e/tests/functions.bats
  pkg/function-manager/controller.go
  pkg/function-manager/controller_test.go
  pkg/function-manager/handlers.go
  pkg/functions/builder.go
  pkg/functions/docker/driver.go
  pkg/functions/docker/driver_test.go
  pkg/functions/mocks/image_builder.go
  pkg/functions/types.go
  pkg/image-manager/controller.go
  pkg/image-manager/handlers.go
  pkg/image-manager/image_builder.go
  pkg/images/builder.go
Labels: cla-not-required, run-e2e

#571 Optimizing image pulls in image manager
  pkg/dispatchserver/config.go
  pkg/dispatchserver/images.go
  pkg/entity-store/postgres.go
  pkg/functions/docker/driver_test.go
  pkg/functions/docker/mocks/docker_client.go
  pkg/image-manager/controller.go
  pkg/image-manager/entities.go
  pkg/image-manager/image_builder.go
  pkg/image-manager/image_builder_test.go
  pkg/image-manager/mocks/image_api_client.go
  pkg/mocks/docker/common_api_client.go
Labels: cla-not-required, run-e2e

#574 [CI base image] Update pipeline and move out tests
  ci/base-images/run-tests.sh
  ci/base-images/tests/clojure/task.yml
  ci/base-images/tests/clojure/tests.bats
  ci/base-images/tests/java/task.yml
  ci/base-images/tests/java/tests.bats
  ci/base-images/tests/nodejs/task.yml
  ci/base-images/tests/nodejs/tests.bats
  ci/base-images/tests/powershell/task.yml
  ci/base-images/tests/powershell/tests.bats
  ci/base-images/tests/python3/task.yml
  ci/base-images/tests/python3/tests.bats
  ci/pipelines/base-images.yml
Labels: cla-not-required

#573 Nkaashoek/ZookeeperScaling
  Gopkg.lock
  charts/dispatch/charts/api-manager/templates/deployment.yaml
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/function-manager/templates/deployment.yaml
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  charts/dispatch/charts/image-manager/templates/deployment.yaml
  charts/dispatch/charts/service-manager/templates/deployment.yaml
  charts/dispatch/values.yaml
  lib/riff/requester.go
  pkg/api-manager/controller.go
  pkg/api-manager/controller_test.go
  pkg/api-manager/handlers.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/dispatchcli/cmd/uninstall.go
  pkg/dispatchcli/cmd/uninstall_test.go
  pkg/dispatchserver/apis.go
  pkg/dispatchserver/config.go
  pkg/dispatchserver/events.go
  pkg/dispatchserver/functions.go
  pkg/dispatchserver/identity.go
  pkg/dispatchserver/images.go
  pkg/dispatchserver/services.go
  pkg/entity-store/postgres.go
  pkg/event-manager/controller.go
  pkg/event-manager/controller_test.go
  pkg/function-manager/controller.go
  pkg/functions/riff/driver.go
  pkg/functions/riff/requester.go
  pkg/functions/runner/runner.go
  pkg/identity-manager/controller.go
  pkg/image-manager/controller.go
  pkg/service-manager/controller.go
  pkg/zookeeper/mocks/Driver.go
  pkg/zookeeper/mocks/OwnershipChecker.go
  pkg/zookeeper/zookeeper.go
  vendor/github.com/samuel/go-zookeeper/LICENSE
  vendor/github.com/samuel/go-zookeeper/zk/conn.go
  vendor/github.com/samuel/go-zookeeper/zk/constants.go
  vendor/github.com/samuel/go-zookeeper/zk/dnshostprovider.go
  vendor/github.com/samuel/go-zookeeper/zk/flw.go
  vendor/github.com/samuel/go-zookeeper/zk/lock.go
  vendor/github.com/samuel/go-zookeeper/zk/server_help.go
  vendor/github.com/samuel/go-zookeeper/zk/server_java.go
  vendor/github.com/samuel/go-zookeeper/zk/structs.go
  vendor/github.com/samuel/go-zookeeper/zk/util.go
Labels: cla-not-required, run-e2e

#582 Add unit tests to base image pipeline
  ci/pipelines/base-images.yml
Labels: cla-not-required

#583 Remove redundant resources in base images CI pipeline
  ci/pipelines/base-images.yml
Labels: cla-not-required
