Repository vmware/dispatch, pull requests merged in 2018-10, with the labels that each got.

#636 Add installer script/image for knative
  .gitignore
  images/knative-installer-gke/Dockerfile
  images/knative-installer-gke/setup_knative.sh
  scripts/install-knative.py
Labels: cla-not-required

#632 Adding a new zookeeper-less controller used when no zookeeper configured
  pkg/api-manager/controller.go
  pkg/api-manager/controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/dispatchserver/apis.go
  pkg/dispatchserver/config.go
  pkg/dispatchserver/events.go
  pkg/dispatchserver/functions.go
  pkg/dispatchserver/identity.go
  pkg/dispatchserver/images.go
  pkg/dispatchserver/services.go
  pkg/event-manager/controller.go
  pkg/event-manager/controller_test.go
  pkg/function-manager/controller.go
  pkg/identity-manager/controller.go
  pkg/image-manager/controller.go
  pkg/service-manager/controller.go
Labels: cla-not-required

#648 Update seed images to knative
  images.yaml
  pkg/dispatchcli/cmd/get_baseimage.go
Labels: cla-not-required

#650 Add minio as a dependency and README changes
  README.md
  charts/dispatch/requirements.lock
  charts/dispatch/requirements.yaml
  charts/dispatch/values.yaml
  pkg/images/backend/knative.go
  pkg/images/backend/knhelpers.go
  scripts/values.sh
Labels: cla-not-required

#604 Dispatch apply
  pkg/dispatchcli/cmd/apply.go
  pkg/dispatchcli/cmd/cmd.go
Labels: cla-not-required

#681 CLI completion for bash added.
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/completion.go
Labels: cla-not-required

#682 Fix minior issues with OVA build
  Gopkg.lock
  cmd/ovfenv/main.go
  cmd/rpctool/main.go
  cmd/toolbox/main.go
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/doc.go
  vendor/github.com/vmware/govmomi/ovf/env.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
  vendor/github.com/vmware/govmomi/ovf/manager.go
  vendor/github.com/vmware/govmomi/ovf/ovf.go
  vendor/github.com/vmware/govmomi/simulator/license_manager.go
  vendor/github.com/vmware/govmomi/vim25/client.go
  vendor/github.com/vmware/govmomi/vim25/debug/debug.go
  vendor/github.com/vmware/govmomi/vim25/doc.go
  vendor/github.com/vmware/govmomi/vim25/methods/methods.go
  vendor/github.com/vmware/govmomi/vim25/methods/service_content.go
  vendor/github.com/vmware/govmomi/vim25/mo/ancestors.go
  vendor/github.com/vmware/govmomi/vim25/mo/entity.go
  vendor/github.com/vmware/govmomi/vim25/mo/extra.go
  vendor/github.com/vmware/govmomi/vim25/mo/mo.go
  vendor/github.com/vmware/govmomi/vim25/mo/reference.go
  vendor/github.com/vmware/govmomi/vim25/mo/registry.go
  vendor/github.com/vmware/govmomi/vim25/mo/retrieve.go
  vendor/github.com/vmware/govmomi/vim25/mo/type_info.go
  vendor/github.com/vmware/govmomi/vim25/progress/aggregator.go
  vendor/github.com/vmware/govmomi/vim25/progress/doc.go
  vendor/github.com/vmware/govmomi/vim25/progress/prefix.go
  vendor/github.com/vmware/govmomi/vim25/progress/reader.go
  vendor/github.com/vmware/govmomi/vim25/progress/report.go
  vendor/github.com/vmware/govmomi/vim25/progress/scale.go
  vendor/github.com/vmware/govmomi/vim25/progress/sinker.go
  vendor/github.com/vmware/govmomi/vim25/progress/tee.go
  vendor/github.com/vmware/govmomi/vim25/retry.go
  vendor/github.com/vmware/govmomi/vim25/soap/client.go
  vendor/github.com/vmware/govmomi/vim25/soap/debug.go
  vendor/github.com/vmware/govmomi/vim25/soap/error.go
  vendor/github.com/vmware/govmomi/vim25/soap/soap.go
  vendor/github.com/vmware/govmomi/vim25/types/base.go
  vendor/github.com/vmware/govmomi/vim25/types/enum.go
  vendor/github.com/vmware/govmomi/vim25/types/fault.go
  vendor/github.com/vmware/govmomi/vim25/types/helpers.go
  vendor/github.com/vmware/govmomi/vim25/types/if.go
  vendor/github.com/vmware/govmomi/vim25/types/registry.go
  vendor/github.com/vmware/govmomi/vim25/types/types.go
  vendor/github.com/vmware/govmomi/vim25/xml/extras.go
  vendor/github.com/vmware/govmomi/vim25/xml/marshal.go
  vendor/github.com/vmware/govmomi/vim25/xml/read.go
  vendor/github.com/vmware/govmomi/vim25/xml/typeinfo.go
  vendor/github.com/vmware/govmomi/vim25/xml/xml.go
Labels: cla-not-required

#684 Dispatch edit command
  README.md
  pkg/dispatchcli/cmd/apply.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/completion.go
  pkg/dispatchcli/cmd/edit.go
Labels: cla-not-required

#687 Example added for CLI completion command.
  pkg/dispatchcli/cmd/completion.go
Labels: cla-not-required

#673 Updates e2e to run against Dispatch solo
  ci/e2e/build-cli.yml
  ci/e2e/cleanup.yml
  ci/e2e/collect-logs.yml
  ci/e2e/config-gke-env.sh
  ci/e2e/config-k8s-env.sh
  ci/e2e/configs/dispatch-config-gke.json
  ci/e2e/configs/dispatch-config-local.json
  ci/e2e/configs/dispatch-install-gke.yml
  ci/e2e/gke-cluster-create.yml
  ci/e2e/prepare-images.yml
  ci/e2e/run-tests.yml
  ci/e2e/uninstall-dispatch.yml
  ci/pipelines/e2e.yml
  e2e/tests/apis.bats
  e2e/tests/events.bats
  e2e/tests/functions.bats
  e2e/tests/images.bats
  e2e/tests/login.bats
  e2e/tests/organizations.bats
  e2e/tests/services.bats
  e2e/tests/variables.bash
Labels: cla-not-required, run-e2e-solo

#685 Solo: Docker Backend for Event Driver
  examples/event-drivers/go/ticker-driver/Dockerfile
  examples/event-drivers/go/ticker-driver/Gopkg.lock
  examples/event-drivers/go/ticker-driver/Gopkg.toml
  examples/event-drivers/go/ticker-driver/driver.go
  pkg/dispatchserver/local.go
  pkg/event-manager/drivers/docker_backend.go
  pkg/event-manager/drivers/entity_handler.go
  pkg/events/driverclient/client.go
  pkg/events/driverclient/http.go
Labels: Solo, cla-not-required

#692 Rebuild API cache from entitystore
  pkg/api-manager/gateway/local/gateway.go
  pkg/api-manager/gateway/local/gateway_test.go
  pkg/api-manager/handlers.go
  pkg/dispatchserver/local.go
Labels: cla-not-required

#694 Improve make help output
  Makefile
Labels: cla-not-required

#697 Clean up references to VIC in OVA packaging code
  scripts/ova/bootable/config/builder.ovf
  scripts/ova/scripts/systemd/scripts/set_guestinfo.sh
  scripts/ova/scripts/systemd/units/storage-db.mount
  scripts/ova/scripts/systemd/units/storage-log.mount
Labels: cla-not-required

#698 Small changes to fix e2e errors in dispatch-solo
  ci/e2e/configs/dispatch-config-local.json
  ci/e2e/run-tests.yml
  e2e/tests/images.bats
  pkg/api-manager/controller.go
Labels: run-e2e-solo

#707 Fix image creation/deletion issue
  e2e/tests/functions.bats
  e2e/tests/helpers.bash
  e2e/tests/images.bats
  e2e/tests/secrets.bats
  e2e/tests/variables.bash
  pkg/image-manager/handlers.go
  pkg/image-manager/handlers_test.go
Labels: cla-not-required, run-e2e-solo
