Repository vmware/dispatch, pull requests merged in 2018-05, with the labels that each got.

#404 Updated license files from legal
  LICENSE.txt
  NOTICE.txt
  open_source_license_dispatch_2018.txt
Labels: cla-not-required

#402 Add the link to our blog
  docs/_layouts/community.html
  docs/assets/images/medium-small-200.png
Labels: cla-not-required

#406 Make the Dispatch license detectable by licensee
  LICENSE
  LICENSE.txt
  NOTICE
  NOTICE.txt
Labels: cla-not-required

#405 Add boolean config support and secret as env variable for event manager
  pkg/dispatchcli/cmd/create_eventdriver.go
  pkg/dispatchcli/cmd/get_eventdriver.go
  pkg/event-manager/drivers/k8s_backend.go
Labels: run-e2e

#412 Update Github issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_question.md
Labels: cla-not-required

#411 [e2e/java] Update function tests to test Spring support
  e2e/tests/functions.bats
  e2e/tests/images.yaml
  examples/java8/HelloSpring.java
  examples/java8/pom.xml
  examples/java8/spring-pom.xml
Labels: cla-not-required, run-e2e

#425 Fix IAM documentation
  docs/_guides/setup-authentication.md
  docs/_guides/setup-service-acccount-authentication.md
Labels: cla-not-required

#438 Adding support for private registries (image pull)
  charts/dispatch/charts/function-manager/templates/config-map.yaml
  charts/dispatch/charts/function-manager/values.yaml
  charts/openfaas/templates/rbac.yaml
  cmd/function-manager/main.go
  docs/_guides/advanced.md
  pkg/config/config.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/functions/builder.go
  pkg/functions/openfaas/driver.go
Labels: cla-not-required, run-e2e

#423 Implement error types for functions
  e2e/tests/functions.bats
  pkg/api-manager/gen/restapi/embedded_spec.go
  pkg/api/v1/error.go
  pkg/api/v1/error_type.go
  pkg/api/v1/invocation_error.go
  pkg/api/v1/run.go
  pkg/application-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/controller.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/functions/context.go
  pkg/functions/context_test.go
  pkg/functions/entities.go
  pkg/functions/injectors/errors.go
  pkg/functions/openfaas/driver.go
  pkg/functions/openwhisk/driver.go
  pkg/functions/riff/driver.go
  pkg/functions/types.go
  pkg/functions/validator/validator.go
  pkg/functions/validator/validator_test.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/secret-store/gen/restapi/embedded_spec.go
  pkg/service-manager/gen/restapi/embedded_spec.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#442 Use command string in generate script to ensure consistency
  ci/units/swagger-generate.yml
  scripts/generate-models.sh
  scripts/generate.sh
Labels: cla-not-required

#443 use Flat JSON which is already generated by Go Swagger
  cmd/api-manager/main.go
  cmd/application-manager/main.go
  cmd/event-manager/main.go
  cmd/function-manager/main.go
  cmd/identity-manager/main.go
  cmd/image-manager/main.go
  cmd/secret-store/main.go
  cmd/service-manager/main.go
  pkg/api-manager/gen/restapi/configure_api_manager.go
  pkg/api-manager/gen/restapi/embedded_spec.go
  pkg/application-manager/gen/restapi/configure_application_manager.go
  pkg/application-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/gen/restapi/configure_event_manager.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/configure_function_manager.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/configure_identity_manager.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/configure_image_manager.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/secret-store/gen/restapi/configure_secret_store.go
  pkg/secret-store/gen/restapi/embedded_spec.go
  pkg/service-manager/gen/restapi/configure_service_manager.go
  pkg/service-manager/gen/restapi/embedded_spec.go
  scripts/generate.sh
Labels: run-e2e

#445 Add dispatch log command
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/log.go
Labels: cla-not-required

#427 Letsencrypt support via cert-manager
  charts/certificate/.helmignore
  charts/certificate/Chart.yaml
  charts/certificate/templates/NOTES.txt
  charts/certificate/templates/_helpers.tpl
  charts/certificate/templates/certificate.yaml
  charts/certificate/templates/clusterissuer.yaml
  charts/certificate/values.yaml
  charts/dispatch/charts/api-manager/templates/deployment.yaml
  charts/dispatch/charts/api-manager/values.yaml
  charts/dispatch/charts/application-manager/templates/deployment.yaml
  charts/dispatch/charts/application-manager/values.yaml
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/event-manager/values.yaml
  charts/dispatch/charts/function-manager/templates/deployment.yaml
  charts/dispatch/charts/function-manager/values.yaml
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  charts/dispatch/charts/identity-manager/values.yaml
  charts/dispatch/charts/image-manager/templates/deployment.yaml
  charts/dispatch/charts/image-manager/values.yaml
  charts/dispatch/charts/secret-store/templates/deployment.yaml
  charts/dispatch/charts/secret-store/values.yaml
  charts/dispatch/charts/service-manager/templates/deployment.yaml
  charts/dispatch/charts/service-manager/values.yaml
  charts/dispatch/values.yaml
  charts/kong/templates/deployment.yaml
  charts/kong/values.yaml
  docs/_guides/gke.md
  docs/_guides/minikube.md
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
Labels: cla-not-required, run-e2e

#448 Include K8S client's OIDC auth plugin in CLI
  Gopkg.lock
  pkg/dispatchcli/cmd/manage.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
Labels: cla-not-required

#446 Add client libraries for Dispatch services
  Gopkg.lock
  cmd/function-manager/main.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/functions.go
  pkg/client/functions_test.go
  pkg/client/images.go
  pkg/client/images_test.go
  pkg/client/mocks/images_client.go
  pkg/client/mocks/secrets_client.go
  pkg/client/mocks/services_client.go
  pkg/client/secrets.go
  pkg/client/secrets_test.go
  pkg/client/services.go
  pkg/client/services_test.go
  pkg/client/tracing.go
  pkg/client/tracing_test.go
  pkg/function-manager/controller.go
  pkg/function-manager/controller_test.go
  pkg/function-manager/handlers.go
  pkg/function-manager/mocks/image_getter.go
  pkg/function-manager/mocks/image_manager.go
  pkg/functions/injectors/secretinjector.go
  pkg/functions/injectors/secretinjector_test.go
  pkg/functions/injectors/serviceinjector.go
  pkg/functions/injectors/serviceinjector_test.go
  pkg/service-manager/clients/k8s_service_catalog.go
  pkg/service-manager/clients/types.go
  pkg/testing/fakeserver/server.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mocklogrecord.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mockspan.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mocktracer.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/propagation.go
Labels: run-e2e

#456 read environment variables in built-in event driver
  pkg/event-driver/cmd/cmd.go
  pkg/event-driver/cmd/vcenter_test.go
Labels: cla-not-required

#455 add missing event-sidecar image to release pipeline
  ci/pipelines/release.yml
Labels: cla-not-required

#458 Unmarshal the event payload if content type is set to JSON
  pkg/event-manager/subscriptions/manager.go
Labels: cla-not-required, run-e2e

#464 Skip service manager tests
  e2e/tests/services.bats
Labels: run-e2e

#440 [WIP] Kubeless driver
  Gopkg.lock
  Gopkg.toml
  cmd/function-manager/main.go
  pkg/config/config.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/functions/kubeless/driver.go
  pkg/functions/kubeless/driver_test.go
  vendor/github.com/kubeless/kubeless/LICENSE
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/register.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/cronjob_trigger.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/doc.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/function.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/http_trigger.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/kafka_trigger.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/nats_trigger.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/register.go
  vendor/github.com/kubeless/kubeless/pkg/apis/kubeless/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/fake/doc.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/cronjobtrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/doc.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/doc.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_cronjobtrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_function.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_httptrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_kafkatrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_kubeless_client.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/fake/fake_natstrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/function.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/generated_expansion.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/httptrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/kafkatrigger.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/kubeless_client.go
  vendor/github.com/kubeless/kubeless/pkg/client/clientset/versioned/typed/kubeless/v1beta1/natstrigger.go
Labels: run-e2e

#424 Add Error Handling spec
  docs/_specs/error-handling/error-handling.md
Labels: cla-not-required

#474 CLI: create function: support single-file functions
  docs/_guides/quickstart.md
  docs/_guides/setup-service-acccount-authentication.md
  docs/_specs/language-support/language-support.md
  e2e/tests/api_update.yaml
  e2e/tests/apis.bats
  e2e/tests/application.bats
  e2e/tests/events.bats
  e2e/tests/functions.bats
  e2e/tests/image_not_found_update.yaml
  e2e/tests/images.bats
  e2e/tests/images.yaml
  e2e/tests/images_update.yaml
  e2e/tests/secrets.bats
  e2e/tests/services.bats
  e2e/tests/update-source/hello.py
  e2e/tests/variables.bash
  examples/bingo/README.md
  examples/blog/README.md
  examples/nodejs/debug.js
  examples/nodejs/echo.js
  examples/nodejs/hello-logs.js
  examples/nodejs/hello.js
  examples/nodejs/hello.schema.in.json
  examples/nodejs/hello.schema.out.json
  examples/nodejs/i-have-a-secret.js
  examples/nodejs/secret.json
  examples/python3/clonevm.py
  examples/python3/gettemplates.py
  examples/python3/getvms.py
  examples/python3/hello.py
  examples/python3/postgres/postgres.py
  examples/seed.yaml
  examples/vcenter/README.md
  examples/web/README.md
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_function.go
  pkg/dispatchcli/cmd/errors.go
  pkg/functions/builder_test.go
  pkg/image-manager/image_builder_test.go
  pkg/images/builder.go
  pkg/utils/tar.go
Labels: cla-not-required, run-e2e

#477 [kong/api] Send empty response from gateway if function output is null
  charts/kong/dispatch-transformer/handler.lua
Labels: cla-not-required

#478 Add switchable contexts for config
  ci/e2e/configs/dispatch-config-gke.json
  ci/e2e/configs/dispatch-config-local.json
  ci/e2e/deploy-dispatch.yml
  ci/e2e/run-tests.yml
  examples/seed.yaml
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/login.go
  pkg/dispatchcli/cmd/logout.go
  pkg/dispatchcli/cmd/manage.go
  pkg/dispatchcli/cmd/manage_context.go
  scripts/push-charts.sh
Labels: cla-not-required, run-e2e

#481 Fix viper flag/env binding
  pkg/dispatchcli/cmd/auth.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/cmd_test.go
Labels: cla-not-required, run-e2e

#482 Documentation and site updates
  docs/_config.yml
  docs/_includes/footer.html
  docs/_includes/head.html
  docs/_layouts/default.html
  docs/_posts/2018-02-01-february-2018-release.md
  docs/_posts/2018-03-02-march-2018-release.md
  docs/_posts/2018-05-23-v0-1-15-release.md
  docs/_usage/api.md
  docs/_usage/event-drivers.md
  docs/_usage/functions.md
  docs/_usage/iam.md
  docs/_usage/images.md
  docs/_usage/services.md
  docs/assets/css/style.scss
  docs/assets/node_modules/anchor-js/.eslintrc
  docs/assets/node_modules/anchor-js/.gitattributes
  docs/assets/node_modules/anchor-js/.npmignore
  docs/assets/node_modules/anchor-js/.travis.yml
  docs/assets/node_modules/anchor-js/README.md
  docs/assets/node_modules/anchor-js/anchor.js
  docs/assets/node_modules/anchor-js/anchor.min.js
  docs/assets/node_modules/anchor-js/banner.js
  docs/assets/node_modules/anchor-js/bower.json
  docs/assets/node_modules/anchor-js/docs/anchor.js
  docs/assets/node_modules/anchor-js/docs/favicon.ico
  docs/assets/node_modules/anchor-js/docs/fonts/anchorjs-extras.eot
  docs/assets/node_modules/anchor-js/docs/fonts/anchorjs-extras.svg
  docs/assets/node_modules/anchor-js/docs/fonts/anchorjs-extras.ttf
  docs/assets/node_modules/anchor-js/docs/fonts/anchorjs-extras.woff
  docs/assets/node_modules/anchor-js/docs/fonts/fonts.css
  docs/assets/node_modules/anchor-js/docs/grunticon/grunticon.loader.js
  docs/assets/node_modules/anchor-js/docs/grunticon/icons.data.png.css
  docs/assets/node_modules/anchor-js/docs/grunticon/icons.data.svg.css
  docs/assets/node_modules/anchor-js/docs/grunticon/icons.fallback.css
  docs/assets/node_modules/anchor-js/docs/grunticon/png/grunticon-link.png
  docs/assets/node_modules/anchor-js/docs/grunticon/preview.html
  docs/assets/node_modules/anchor-js/docs/img/anchoring-links.png
  docs/assets/node_modules/anchor-js/docs/img/anchorjs_logo.png
  docs/assets/node_modules/anchor-js/docs/img/anchorlinks2.png
  docs/assets/node_modules/anchor-js/docs/img/gh-link.svg
  docs/assets/node_modules/anchor-js/docs/img/gh_link.svg
  docs/assets/node_modules/anchor-js/docs/img/hyperlink.svg
  docs/assets/node_modules/anchor-js/docs/img/link.svg
  docs/assets/node_modules/anchor-js/docs/img/mini-logo.png
  docs/assets/node_modules/anchor-js/docs/img/primer-md.png
  docs/assets/node_modules/anchor-js/docs/index.html
  docs/assets/node_modules/anchor-js/docs/scripts.js
  docs/assets/node_modules/anchor-js/docs/styles.css
  docs/assets/node_modules/anchor-js/package.json
  docs/assets/node_modules/anchor-js/test/SpecRunner.html
  docs/assets/node_modules/anchor-js/test/config.js
  docs/assets/node_modules/anchor-js/test/load-order-1.html
  docs/assets/node_modules/anchor-js/test/load-order-2.html
  docs/assets/node_modules/anchor-js/test/load-order-3.html
  docs/assets/node_modules/anchor-js/test/spec/AnchorSpec.js
  docs/assets/node_modules/anchor-js/test/visual-check.html
  docs/assets/package-lock.json
Labels: cla-not-required, run-e2e
