Repository vmware/dispatch, pull requests merged in 2018-04, with the labels that each got.

#347 Changed create function code from 200 to 201
  pkg/function-manager/gen/client/store/add_function_responses.go
  pkg/function-manager/gen/client/store/store_client.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/operations/store/add_function_responses.go
  pkg/function-manager/handlers.go
  pkg/function-manager/handlers_test.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#342 Pass HTTP context into function context and fix API gateway bug
  charts/kong/dispatch-transformer/handler.lua
  charts/kong/dispatch-transformer/schema.lua
  cmd/api-manager/main.go
  e2e/tests/apis.bats
  pkg/api-manager/gateway/gateway.go
  pkg/api-manager/gateway/kong/kong.go
  pkg/api-manager/gateway/kong/kong_test.go
  pkg/api-manager/gateway/mocks/Gateway.go
  pkg/function-manager/controller.go
  pkg/function-manager/gen/models/run.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/functions/context.go
  pkg/functions/entities.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#349 Move base images to their own repos
  docs/_guides/quickstart.md
  examples/bingo/README.md
  examples/blog/README.md
  examples/python3/clonevm.py
  examples/python3/gettemplates.py
  examples/python3/getvms.py
  examples/python3/hello.py
  examples/seed.yaml
  examples/vcenter/README.md
  examples/web/README.md
  images/base-images/nodejs6/Dockerfile
  images/base-images/nodejs6/build.sh
  images/base-images/nodejs6/function-server/http-api.js
  images/base-images/nodejs6/function-server/package-lock.json
  images/base-images/nodejs6/function-server/package.json
  images/base-images/nodejs6/function-server/server.js
  images/base-images/nodejs6/function-template/Dockerfile
  images/base-images/nodejs6/function.js
  images/base-images/nodejs6/image-template/Dockerfile
  images/base-images/powershell/Dockerfile
  images/base-images/powershell/build.sh
  images/base-images/powershell/function-template/Dockerfile
  images/base-images/powershell/function/handler.ps1
  images/base-images/powershell/image-template/Dockerfile
  images/base-images/powershell/index.ps1
  images/base-images/python3/Dockerfile
  images/base-images/python3/build.sh
  images/base-images/python3/function-server/function/handler.py
  images/base-images/python3/function-server/main.py
  images/base-images/python3/function-server/requirements.txt
  images/base-images/python3/function-template/Dockerfile
  images/base-images/python3/image-template/Dockerfile
  pkg/dispatchcli/cmd/update_baseimage.go
  pkg/functions/openfaas/driver_test.go
Labels: cla-not-required

#351 Add Kafka backend for events and make it default
  Gopkg.lock
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/event-manager/values.yaml
  charts/dispatch/charts/function-manager/templates/config-map.yaml
  charts/dispatch/charts/function-manager/values.yaml
  charts/dispatch/values.yaml
  ci/e2e/cleanup.yml
  cmd/event-manager/main.go
  docs/_guides/working-with-events.md
  e2e/tests/events.bats
  pkg/dispatchcli/cmd/create_subscription.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/dispatchcli/cmd/uninstall.go
  pkg/event-manager/drivers/http_handlers.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-manager/gen/models/subscription.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/handlers.go
  pkg/event-manager/handlers_test.go
  pkg/event-manager/subscriptions/http_handlers_test.go
  pkg/event-manager/subscriptions/manager.go
  pkg/event-sidecar/cmd.go
  pkg/events/transport/kafka.go
  pkg/events/transport/kafka_test.go
  swagger/event-manager.yaml
  vendor/github.com/Shopify/sarama/mocks/README.md
  vendor/github.com/Shopify/sarama/mocks/async_producer.go
  vendor/github.com/Shopify/sarama/mocks/consumer.go
  vendor/github.com/Shopify/sarama/mocks/mocks.go
  vendor/github.com/Shopify/sarama/mocks/sync_producer.go
Labels: cla-not-required, run-e2e

#327 [cli/update] update e2e tests to use file based update mechanic
  e2e/tests/api_update.yaml
  e2e/tests/apis.bats
  e2e/tests/image_not_found_update.yaml
  e2e/tests/images.bats
  e2e/tests/images_update.yaml
  e2e/tests/secret_update.yaml
  e2e/tests/secrets.bats
  pkg/dispatchcli/cmd/update.go
  pkg/dispatchcli/cmd/update_api.go
  pkg/dispatchcli/cmd/update_application.go
  pkg/dispatchcli/cmd/update_baseimage.go
  pkg/dispatchcli/cmd/update_image.go
  pkg/dispatchcli/cmd/update_policy.go
  pkg/dispatchcli/cmd/update_secret.go
Labels: cla-not-required, run-e2e

#348 [CLI support] Generate JWT token for service account
  Gopkg.lock
  pkg/dispatchcli/cmd/auth.go
  pkg/dispatchcli/cmd/cmd.go
  vendor/github.com/dgrijalva/jwt-go/.gitignore
  vendor/github.com/dgrijalva/jwt-go/.travis.yml
  vendor/github.com/dgrijalva/jwt-go/LICENSE
  vendor/github.com/dgrijalva/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/dgrijalva/jwt-go/README.md
  vendor/github.com/dgrijalva/jwt-go/VERSION_HISTORY.md
  vendor/github.com/dgrijalva/jwt-go/claims.go
  vendor/github.com/dgrijalva/jwt-go/doc.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa.go
  vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/errors.go
  vendor/github.com/dgrijalva/jwt-go/hmac.go
  vendor/github.com/dgrijalva/jwt-go/map_claims.go
  vendor/github.com/dgrijalva/jwt-go/none.go
  vendor/github.com/dgrijalva/jwt-go/parser.go
  vendor/github.com/dgrijalva/jwt-go/rsa.go
  vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
  vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
  vendor/github.com/dgrijalva/jwt-go/signing_method.go
  vendor/github.com/dgrijalva/jwt-go/token.go
Labels: cla-not-required

#360 Add Bearer Auth handler to other services
  pkg/api-manager/handlers.go
  pkg/application-manager/handlers.go
  pkg/event-manager/handlers.go
  pkg/function-manager/handlers.go
  pkg/identity-manager/gen/client/operations/operations_client.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/operations/home.go
  pkg/identity-manager/gen/restapi/operations/root.go
  pkg/image-manager/handlers.go
  pkg/secret-store/web/handlers.go
  pkg/service-manager/gen/restapi/configure_service_manager.go
  pkg/service-manager/gen/restapi/embedded_spec.go
  pkg/service-manager/gen/restapi/operations/service_manager_api.go
  pkg/service-manager/handlers.go
  swagger/identity-manager.yaml
  swagger/service-manager.yaml
Labels: cla-not-required, run-e2e

#338 [cli/update] add update functionality for functions in dispatch cli
  e2e/tests/function_update.yaml
  e2e/tests/functions.bats
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/update.go
  pkg/dispatchcli/cmd/update_function.go
  pkg/function-manager/controller.go
  pkg/function-manager/gen/models/function.go
  pkg/function-manager/gen/models/run.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/functions/entities.go
  pkg/functions/openfaas/driver.go
  pkg/functions/openfaas/driver_test.go
  pkg/functions/openwhisk/driver.go
  pkg/functions/types.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#365 Fix few bugs related to event manager
  ci/Makefile
  ci/e2e/configs/dispatch-install-gke.yml
  ci/e2e/configs/dispatch-install-local.yml
  ci/e2e/deploy-dispatch.yml
  ci/e2e/run-tests.yml
  ci/pipelines/e2e.yml
  cmd/event-manager/main.go
  e2e/tests/events.bats
  e2e/tests/helpers.bash
  e2e/tests/variables.bash
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-sidecar/cmd.go
  pkg/events/transport/kafka.go
Labels: cla-not-required, run-e2e

#361 Add `iam` subcommand to CLI and support for ServiceAccount
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/delete.go
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/get.go
  pkg/dispatchcli/cmd/iam.go
  pkg/dispatchcli/cmd/iam_create.go
  pkg/dispatchcli/cmd/iam_create_policy.go
  pkg/dispatchcli/cmd/iam_create_policy_test.go
  pkg/dispatchcli/cmd/iam_create_serviceaccount.go
  pkg/dispatchcli/cmd/iam_delete.go
  pkg/dispatchcli/cmd/iam_delete_policy.go
  pkg/dispatchcli/cmd/iam_delete_serviceaccount.go
  pkg/dispatchcli/cmd/iam_get.go
  pkg/dispatchcli/cmd/iam_get_policy.go
  pkg/dispatchcli/cmd/iam_get_serviceaccount.go
  pkg/dispatchcli/cmd/update.go
  pkg/identity-manager/gen/models/policy.go
  pkg/identity-manager/gen/models/service_account.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/policy_api_handler.go
  pkg/identity-manager/service_account_api_handler.go
  pkg/utils/constants.go
  swagger/identity-manager.yaml
Labels: cla-not-required

#366 Support bearer token in bootstrap mode
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  charts/dispatch/charts/identity-manager/templates/secret.yaml
  charts/dispatch/charts/identity-manager/values.yaml
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
Labels: cla-not-required, run-e2e

#367 Enhance chart controls for RBAC, Resource limits, Ingress
  charts/dispatch/charts/api-manager/templates/deployment.yaml
  charts/dispatch/charts/application-manager/templates/deployment.yaml
  charts/dispatch/charts/echo-server/templates/deployment.yaml
  charts/dispatch/charts/event-manager/templates/cluster-role.yaml
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/charts/event-manager/templates/role-binding.yaml
  charts/dispatch/charts/event-manager/templates/service-account.yaml
  charts/dispatch/charts/function-manager/templates/cluster-role-binding.yaml
  charts/dispatch/charts/function-manager/templates/cluster-role.yaml
  charts/dispatch/charts/function-manager/templates/deployment.yaml
  charts/dispatch/charts/function-manager/templates/service-account.yaml
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  charts/dispatch/charts/identity-manager/templates/ingress.noauth.yaml
  charts/dispatch/charts/identity-manager/values.yaml
  charts/dispatch/charts/image-manager/templates/deployment.yaml
  charts/dispatch/charts/secret-store/templates/cluster-role.yaml
  charts/dispatch/charts/secret-store/templates/deployment.yaml
  charts/dispatch/charts/secret-store/templates/role-binding.yaml
  charts/dispatch/charts/secret-store/templates/service-account.yaml
  charts/dispatch/templates/_helpers.tpl
  charts/dispatch/values.yaml
  charts/kong/templates/deployment.yaml
  charts/openfaas/templates/faas.yaml
  charts/openfaas/templates/monitoring.yaml
  charts/openfaas/templates/nats.yaml
  charts/openfaas/values.yaml
Labels: cla-not-required, run-e2e

#369 Make Dispatch work on Docker for Mac
  docs/_guides/docker-for-mac.md
  pkg/dispatchcli/cmd/install.go
Labels: cla-not-required

#373 Workaround for scheduling issue in concourse
  ci/pipelines/e2e.yml
Labels: run-e2e

#374 update the postgres example to match blog
  examples/python3/postgres/postgres.py
Labels: cla-not-required

#375 Add `manage` subcommand for Dispatch enable/disable bootstrap mode
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/iam_create_serviceaccount.go
  pkg/dispatchcli/cmd/manage.go
Labels: cla-not-required

#372 Enable Auth in CI
  charts/dispatch/charts/identity-manager/templates/bootstrap-secret.yaml
  charts/dispatch/charts/identity-manager/templates/deployment.yaml
  ci/Makefile
  ci/e2e/configs/dispatch-install-gke.yml
  ci/e2e/configs/dispatch-install-local.yml
  ci/e2e/deploy-dispatch.yml
  ci/e2e/run-tests.yml
  pkg/dispatchcli/cmd/auth.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
  pkg/identity-manager/testdata/bootstrap_public_key
  pkg/identity-manager/testdata/bootstrap_user
Labels: run-e2e

#371 [events/e2e] Add eventdriver and subscription update test to e2e
  e2e/tests/application.bats
  e2e/tests/events.bats
  e2e/tests/services.bats
Labels: cla-not-required, run-e2e

#381 [api/secrets] Fix 500 when secret not found
  pkg/secret-store/service/k8s_secrets_service.go
  pkg/secret-store/service/k8s_secrets_service_test.go
  pkg/secret-store/web/handlers.go
Labels: cla-not-required, run-e2e

#378 Add missing service tests
  pkg/service-manager/clients/k8s_service_catalog.go
  pkg/service-manager/controller.go
  pkg/service-manager/controller_test.go
  pkg/service-manager/entities/entities.go
  pkg/service-manager/handlers.go
  pkg/service-manager/handlers_test.go
Labels: run-e2e

#384 Encode public key when enable bootstrap mode
  pkg/dispatchcli/cmd/manage.go
Labels: cla-not-required

#390 Upgrade gke cluster version
  ci/e2e/gke-cluster-create.yml
Labels: cla-not-required, run-e2e

#388 Update auth docs
  docs/_guides/setup-authentication.md
Labels: cla-not-required

#386 Add guide for setting up service account authentication
  docs/_guides/setup-service-acccount-authentication.md
Labels: cla-not-required

#393 fixing service e2e tests and gke install
  ci/e2e/configs/dispatch-config-gke.json
  ci/e2e/gke-cluster-create.yml
  docs/_guides/setup-authentication.md
  e2e/tests/helpers.bash
  e2e/tests/services.bats
  pkg/dispatchcli/cmd/get_serviceclass.go
  pkg/dispatchcli/cmd/get_serviceinstance.go
  pkg/dispatchcli/cmd/install.go
Labels: cla-not-required, run-e2e

#395 CLI: payload can be any value, not necessarily a map
  e2e/tests/functions.bats
  pkg/dispatchcli/cmd/exec.go
Labels: cla-not-required, run-e2e

#396 Add the Language Support spec
  docs/_specs/language-support/language-support.md
  pkg/functions/builder.go
  pkg/image-manager/image_builder.go
Labels: cla-not-required, run-e2e

#397 Fix the binding reference so that service bidings... delete
  e2e/tests/services.bats
  pkg/service-manager/clients/k8s_service_catalog.go
Labels: cla-not-required, run-e2e

#398 Added stdout to logs
  docs/_guides/quickstart.md
  e2e/tests/function_update.yaml
  e2e/tests/functions.bats
  e2e/tests/image_not_found_update.yaml
  e2e/tests/images.yaml
  e2e/tests/images_update.yaml
  e2e/tests/variables.bash
  examples/bingo/README.md
  examples/blog/README.md
  examples/python3/clonevm.py
  examples/python3/gettemplates.py
  examples/python3/getvms.py
  examples/python3/hello.py
  examples/python3/postgres/postgres.py
  examples/seed.yaml
  examples/vcenter/README.md
  examples/web/README.md
  pkg/function-manager/controller.go
  pkg/function-manager/gen/models/logs.go
  pkg/function-manager/gen/models/run.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/functions/context.go
  pkg/functions/context_test.go
  pkg/functions/entities.go
  pkg/functions/openfaas/driver_test.go
  pkg/image-manager/image_builder_test.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#400 add missing output to deploy-dispatch-riff task
  ci/Makefile
Labels: cla-not-required

#385 Add java examples and e2e tests
  e2e/tests/functions.bats
  e2e/tests/images.bats
  e2e/tests/images.yaml
  e2e/tests/variables.bash
  examples/java8/Hello.java
  examples/java8/HelloWithClasses.java
  examples/java8/HelloWithDeps.java
  examples/java8/pom.xml
Labels: cla-not-required, run-e2e
