Repository vmware/dispatch, pull requests merged in 2018-06, with the labels that each got.

#480 Misc install and chart fixes
  charts/dispatch/charts/image-manager/templates/deployment.yaml
  charts/dispatch/charts/image-manager/values.yaml
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/log.go
  pkg/dispatchcli/cmd/manage.go
Labels: cla-not-required, run-e2e

#487 [function/timeout] Add function timeout to function context
  pkg/api/v1/function.go
  pkg/dispatchcli/cmd/create_function.go
  pkg/function-manager/controller.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/functions/context.go
  pkg/functions/entities.go
  swagger/models.json
Labels: cla-not-required

#490 [git/validate] Fix swagger validation in pre-commit hook
  .githooks/pre-commit
  pkg/api/v1/doc.go
  swagger/models.json
Labels: cla-not-required

#492 Add CHANGELOG
  CHANGELOG.md
Labels: cla-not-required

#491 Add clouddns as supported DNS provider
  charts/certificate/templates/certificate.yaml
  charts/certificate/templates/clusterissuer.yaml
  charts/certificate/values.yaml
  charts/dispatch/values.yaml
  docs/_guides/advanced.md
  docs/_guides/gke.md
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
Labels: cla-not-required

#489 Add Org API/Model/Swagger Defs
  ci/e2e/deploy-dispatch.yml
  pkg/api/v1/organization.go
  pkg/identity-manager/entities.go
  pkg/identity-manager/gen/client/identity_manager_client.go
  pkg/identity-manager/gen/client/organization/add_organization_parameters.go
  pkg/identity-manager/gen/client/organization/add_organization_responses.go
  pkg/identity-manager/gen/client/organization/delete_organization_parameters.go
  pkg/identity-manager/gen/client/organization/delete_organization_responses.go
  pkg/identity-manager/gen/client/organization/get_organization_parameters.go
  pkg/identity-manager/gen/client/organization/get_organization_responses.go
  pkg/identity-manager/gen/client/organization/get_organizations_parameters.go
  pkg/identity-manager/gen/client/organization/get_organizations_responses.go
  pkg/identity-manager/gen/client/organization/organization_client.go
  pkg/identity-manager/gen/client/organization/update_organization_parameters.go
  pkg/identity-manager/gen/client/organization/update_organization_responses.go
  pkg/identity-manager/gen/restapi/configure_identity_manager.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/operations/identity_manager_api.go
  pkg/identity-manager/gen/restapi/operations/organization/add_organization.go
  pkg/identity-manager/gen/restapi/operations/organization/add_organization_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/add_organization_responses.go
  pkg/identity-manager/gen/restapi/operations/organization/add_organization_urlbuilder.go
  pkg/identity-manager/gen/restapi/operations/organization/delete_organization.go
  pkg/identity-manager/gen/restapi/operations/organization/delete_organization_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/delete_organization_responses.go
  pkg/identity-manager/gen/restapi/operations/organization/delete_organization_urlbuilder.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organization.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organization_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organization_responses.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organization_urlbuilder.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organizations.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organizations_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organizations_responses.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organizations_urlbuilder.go
  pkg/identity-manager/gen/restapi/operations/organization/update_organization.go
  pkg/identity-manager/gen/restapi/operations/organization/update_organization_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/update_organization_responses.go
  pkg/identity-manager/gen/restapi/operations/organization/update_organization_urlbuilder.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/org_api_handler.go
  pkg/identity-manager/org_api_handler_test.go
  pkg/utils/constants.go
  swagger/identity-manager.yaml
  swagger/models.json
Labels: cla-not-required, run-e2e

#460 [CLI] Login with service account support
  e2e/tests/login.bats
  pkg/dispatchcli/cmd/auth.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/login.go
  pkg/dispatchcli/cmd/logout.go
Labels: cla-not-required, run-e2e

#494 Fix datatype for entity store regarding timestamp
  e2e/tests/events.bats
  pkg/entity-store/postgres.go
Labels: cla-not-required

#495 create/delete batch operations for all resource types
  examples/seed.yaml
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_api.go
  pkg/dispatchcli/cmd/create_eventdriver.go
  pkg/dispatchcli/cmd/create_eventdrivertype.go
  pkg/dispatchcli/cmd/create_subscription.go
  pkg/dispatchcli/cmd/delete.go
  pkg/dispatchcli/cmd/delete_api.go
  pkg/dispatchcli/cmd/delete_eventdriver.go
  pkg/dispatchcli/cmd/delete_eventdrivertype.go
  pkg/dispatchcli/cmd/delete_subscription.go
  pkg/dispatchcli/cmd/mocks/base_image_client.go
  pkg/dispatchcli/cmd/update.go
Labels: cla-not-required, run-e2e

#496 Release 0.1.16
  CHANGELOG.md
  docs/_posts/2018-06-06-v0-1-16-release.md
Labels: run-e2e

#479 Add a single E2E Test for kong plugin
  e2e/tests/apis.bats
Labels: cla-not-required, run-e2e

#439 Event manager deploy and sync improvement
  e2e/tests/events.bats
  pkg/api/v1/event_driver.go
  pkg/controller/controller.go
  pkg/dispatchcli/cmd/get_eventdriver.go
  pkg/event-manager/drivers/entities/driver.go
  pkg/event-manager/drivers/entity_handler.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-manager/drivers/k8s_errors.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#498 super minor changes to docs.
  docs/_guides/gke.md
  docs/_guides/minikube.md
Labels: cla-not-required

#500 Version API and CLI
  Makefile
  charts/dispatch/charts/identity-manager/values.yaml
  pkg/api/v1/version.go
  pkg/client/version.go
  pkg/dispatchcli/cmd/rest_clients.go
  pkg/dispatchcli/cmd/version.go
  pkg/identity-manager/gen/client/operations/get_version_parameters.go
  pkg/identity-manager/gen/client/operations/get_version_responses.go
  pkg/identity-manager/gen/client/operations/operations_client.go
  pkg/identity-manager/gen/restapi/configure_identity_manager.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/operations/get_version.go
  pkg/identity-manager/gen/restapi/operations/get_version_parameters.go
  pkg/identity-manager/gen/restapi/operations/get_version_responses.go
  pkg/identity-manager/gen/restapi/operations/get_version_urlbuilder.go
  pkg/identity-manager/gen/restapi/operations/identity_manager_api.go
  pkg/identity-manager/handlers.go
  pkg/middleware/health.go
  pkg/version/version.go
  scripts/images.sh
  scripts/values.sh
  swagger/identity-manager.yaml
  swagger/models.json
Labels: cla-not-required, run-e2e

#502 Use client SDK for secrets and services in CLI
  pkg/client/secrets.go
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_baseimage.go
  pkg/dispatchcli/cmd/create_secret.go
  pkg/dispatchcli/cmd/create_secret_test.go
  pkg/dispatchcli/cmd/create_serviceinstance.go
  pkg/dispatchcli/cmd/create_test.go
  pkg/dispatchcli/cmd/delete.go
  pkg/dispatchcli/cmd/delete_secret.go
  pkg/dispatchcli/cmd/delete_serviceinstance.go
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/get_secret.go
  pkg/dispatchcli/cmd/get_serviceclass.go
  pkg/dispatchcli/cmd/get_serviceinstance.go
  pkg/dispatchcli/cmd/rest_clients.go
  pkg/dispatchcli/cmd/update.go
Labels: cla-not-required, run-e2e

#503 Make tests logs optional when collecting logs
  ci/e2e/collect-logs.yml
Labels: cla-not-required, run-e2e

#504 Fix bug with image deletion
  CHANGELOG.md
  pkg/image-manager/controller.go
  pkg/image-manager/handlers.go
Labels: cla-not-required, run-e2e

#505 Add nav to code document
  docs/_includes/header.html
  docs/_usage/images.md
  docs/code.md
  pkg/dispatchcli/cmd/create_baseimage.go
Labels: cla-not-required

#507 CLI: dispatch create seed-images
  Makefile
  docs/_guides/quickstart.md
  docs/_guides/setup-service-acccount-authentication.md
  docs/_specs/language-support/language-support.md
  e2e/tests/events.bats
  e2e/tests/functions.bats
  e2e/tests/helpers.bash
  e2e/tests/image_not_found_update.yaml
  e2e/tests/images.bats
  e2e/tests/images_update.yaml
  e2e/tests/secrets.bats
  e2e/tests/services.bats
  e2e/tests/update-source/hello.py
  e2e/tests/variables.bash
  examples/bingo/README.md
  examples/blog/README.md
  examples/python3/clonevm.py
  examples/python3/gettemplates.py
  examples/python3/getvms.py
  examples/python3/hello.py
  examples/python3/postgres/postgres.py
  examples/seed.yaml
  examples/vcenter/README.md
  examples/web/README.md
  images.yaml
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_seed-images.go
  pkg/image-manager/image_builder_test.go
Labels: cla-not-required, run-e2e

#509 Update CHANGELOG and docs for v0.1.17 release
  CHANGELOG.md
  docs/_posts/2018-06-12-v0-1-17-release.md
Labels: run-e2e

#515 Move to upstream openfaas chart
  Makefile
  charts/openfaas/Chart.yaml
  charts/openfaas/templates/_helpers.tpl
  charts/openfaas/templates/configmaps.yaml
  charts/openfaas/templates/external-service-access.yaml
  charts/openfaas/templates/faas.yaml
  charts/openfaas/templates/ingress.yaml
  charts/openfaas/templates/monitoring.yaml
  charts/openfaas/templates/nats.yaml
  charts/openfaas/templates/rbac.yaml
  charts/openfaas/values.yaml
  e2e/tests/variables.bash
  images.yaml
  pkg/dispatchcli/cmd/install_config.go
  pkg/dispatchcli/cmd/uninstall.go
Labels: cla-not-required, run-e2e

#517 Fix single file java support
  CHANGELOG.md
  e2e/tests/functions.bats
  pkg/functions/builder_test.go
  pkg/utils/tar.go
Labels: cla-not-required, run-e2e

#513 Add reason field to function to hold function creation errors
  CHANGELOG.md
  e2e/tests/functions.bats
  pkg/api/v1/function.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/images/builder.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#521 Make tag configurable during image building
  Makefile
Labels: cla-not-required

#524 Do not return `source` field in /functions API
  pkg/function-manager/handlers.go
  pkg/function-manager/handlers_test.go
  pkg/functions/types.go
Labels: cla-not-required, run-e2e

#514 Minor changes to docs
  docs/_guides/gke.md
  docs/_guides/quickstart.md
Labels: cla-not-required

#526 add eks install docs
  docs/_guides/eks.md
Labels: cla-not-required

#531 Make the event transport compatible with recent multi-org changes
  cmd/event-manager/main.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-manager/handlers.go
  pkg/event-manager/subscriptions/manager.go
  pkg/event-sidecar/cmd.go
  pkg/event-sidecar/listener/http.go
  pkg/event-sidecar/listener/shared.go
  pkg/events/mocks/transport.go
  pkg/events/transport/kafka.go
  pkg/events/transport/kafka_test.go
  pkg/events/transport/noop.go
  pkg/events/transport/rabbitmq.go
  pkg/events/transport/subscription.go
  pkg/events/types.go
Labels: run-e2e

#529 Add Organization CLI and fix tenancy issues
  CHANGELOG.md
  pkg/dispatchcli/cmd/auth.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/create_application.go
  pkg/dispatchcli/cmd/delete_application.go
  pkg/dispatchcli/cmd/get_application.go
  pkg/dispatchcli/cmd/iam_create.go
  pkg/dispatchcli/cmd/iam_create_organization.go
  pkg/dispatchcli/cmd/iam_create_policy.go
  pkg/dispatchcli/cmd/iam_delete.go
  pkg/dispatchcli/cmd/iam_delete_organization.go
  pkg/dispatchcli/cmd/iam_get.go
  pkg/dispatchcli/cmd/iam_get_organization.go
  pkg/dispatchcli/cmd/iam_get_policy.go
  pkg/dispatchcli/cmd/login.go
  pkg/dispatchcli/cmd/manage_bootstrap.go
  pkg/dispatchcli/cmd/rest_clients.go
  pkg/dispatchcli/cmd/update.go
  pkg/identity-manager/org_api_handler.go
  pkg/identity-manager/org_api_handler_test.go
Labels: cla-not-required, run-e2e

#530 Update CHANGELOG and docs for v0.1.18 release
  CHANGELOG.md
  docs/_posts/2018-06-19-v0-1-18-release.md
Labels: run-e2e

#533 Add $KUBECONFIG for k8s config during bootstrap
  pkg/dispatchcli/cmd/manage_bootstrap.go
Labels: cla-not-required

#535 Update CloudEvent implementation to adhere to the latest version
  docs/_guides/working-with-events.md
  e2e/tests/events.bats
  examples/event-drivers/go/ticker-driver/driver.go
  pkg/api/v1/cloud_event.go
  pkg/api/v1/emission.go
  pkg/api/v1/subscription.go
  pkg/dispatchcli/cmd/create_subscription.go
  pkg/dispatchcli/cmd/emit.go
  pkg/dispatchcli/cmd/get_subscription.go
  pkg/event-driver/drivers/vcenter/vcenter.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/handlers.go
  pkg/event-manager/handlers_test.go
  pkg/event-manager/helpers/cloudevent.go
  pkg/event-manager/subscriptions/entities/subscription.go
  pkg/event-manager/subscriptions/http_handlers_test.go
  pkg/event-manager/subscriptions/manager.go
  pkg/event-sidecar/listener/http_test.go
  pkg/event-sidecar/listener/shared_test.go
  pkg/events/cloudevent.go
  pkg/events/parser/json_test.go
  pkg/events/transport/rabbitmq.go
  pkg/events/validator/default_test.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#527 Add model field pattern
  pkg/api-manager/gen/restapi/embedded_spec.go
  pkg/api/v1/api.go
  pkg/api/v1/application.go
  pkg/api/v1/base_image.go
  pkg/api/v1/event_driver.go
  pkg/api/v1/event_driver_type.go
  pkg/api/v1/field_patterns.go
  pkg/api/v1/function.go
  pkg/api/v1/image.go
  pkg/api/v1/policy.go
  pkg/api/v1/secret.go
  pkg/api/v1/service_instance.go
  pkg/api/v1/subscription.go
  pkg/application-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/secret-store/gen/restapi/embedded_spec.go
  pkg/service-manager/gen/restapi/embedded_spec.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#534 Multi-tenancy Enhancements and New E2E Tests
  ci/e2e/deploy-dispatch.yml
  ci/e2e/run-tests.yml
  e2e/tests/helpers.bash
  e2e/tests/login.bats
  e2e/tests/organizations.bats
  pkg/client/identity.go
  pkg/dispatchcli/cmd/cmd.go
  pkg/identity-manager/casbin_entity_adapter.go
  pkg/identity-manager/gen/client/operations/auth_parameters.go
  pkg/identity-manager/gen/client/organization/add_organization_parameters.go
  pkg/identity-manager/gen/client/organization/get_organizations_parameters.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/operations/auth_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/add_organization_parameters.go
  pkg/identity-manager/gen/restapi/operations/organization/get_organizations_parameters.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
  pkg/identity-manager/policy_api_handler_test.go
  pkg/identity-manager/service_account_api_handler_test.go
  pkg/testing/api/api.go
  swagger/identity-manager.yaml
Labels: cla-not-required, run-e2e

#538 Update seed.yaml after Subscription model changes
  examples/seed.yaml
Labels: cla-not-required

#539 Exposable drivers
  CHANGELOG.md
  charts/dispatch/charts/event-manager/templates/cluster-role.yaml
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  cmd/event-manager/main.go
  pkg/api/v1/event_driver.go
  pkg/api/v1/event_driver_type.go
  pkg/dispatchcli/cmd/create_eventdrivertype.go
  pkg/dispatchcli/cmd/get_eventdriver.go
  pkg/dispatchcli/cmd/get_eventdrivertype.go
  pkg/event-manager/drivers/entities/driver.go
  pkg/event-manager/drivers/entities/driver_type.go
  pkg/event-manager/drivers/entity_handler.go
  pkg/event-manager/drivers/entity_handler_test.go
  pkg/event-manager/drivers/http_handlers.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/event-manager/drivers/k8s_errors.go
  pkg/event-manager/drivers/mocks/backend.go
  pkg/event-manager/drivers/types.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/handlers.go
  pkg/events/cloudevent.go
  swagger/models.json
Labels: cla-not-required

#536 fix service manager
  charts/dispatch/charts/service-manager/templates/deployment.yaml
  ci/Makefile
  ci/e2e/collect-logs.yml
  cmd/service-manager/main.go
  e2e/tests/functions.bats
  e2e/tests/services.bats
  pkg/client/mocks/services_client.go
  pkg/client/secrets_test.go
  pkg/client/services.go
  pkg/client/services_test.go
  pkg/dispatchcli/cmd/create_serviceinstance.go
  pkg/dispatchcli/cmd/delete_serviceinstance.go
  pkg/dispatchcli/cmd/get_serviceclass.go
  pkg/dispatchcli/cmd/get_serviceinstance.go
  pkg/event-manager/drivers/k8s_backend.go
  pkg/functions/injectors/serviceinjector.go
  pkg/functions/injectors/serviceinjector_test.go
  pkg/secret-store/service/k8s_secrets_service.go
  pkg/service-manager/clients/k8s_service_catalog.go
  pkg/service-manager/controller.go
  pkg/service-manager/controller_test.go
  pkg/service-manager/entities/entities.go
  pkg/service-manager/flags/flags.go
  pkg/service-manager/gen/client/service_class/get_service_class_by_name_parameters.go
  pkg/service-manager/gen/client/service_class/get_service_classes_parameters.go
  pkg/service-manager/gen/client/service_instance/add_service_instance_parameters.go
  pkg/service-manager/gen/client/service_instance/delete_service_instance_by_name_parameters.go
  pkg/service-manager/gen/client/service_instance/get_service_instance_by_name_parameters.go
  pkg/service-manager/gen/client/service_instance/get_service_instances_parameters.go
  pkg/service-manager/gen/restapi/embedded_spec.go
  pkg/service-manager/gen/restapi/operations/service_class/get_service_class_by_name_parameters.go
  pkg/service-manager/gen/restapi/operations/service_class/get_service_classes_parameters.go
  pkg/service-manager/gen/restapi/operations/service_instance/add_service_instance_parameters.go
  pkg/service-manager/gen/restapi/operations/service_instance/delete_service_instance_by_name_parameters.go
  pkg/service-manager/gen/restapi/operations/service_instance/get_service_instance_by_name_parameters.go
  pkg/service-manager/gen/restapi/operations/service_instance/get_service_instances_parameters.go
  pkg/service-manager/handlers.go
  pkg/service-manager/handlers_test.go
  swagger/service-manager.yaml
Labels: cla-not-required, run-e2e

#540 fix eventdriver name filter: lower letter only
  e2e/tests/events.bats
  pkg/api/v1/event_driver.go
  pkg/api/v1/field_patterns.go
  pkg/event-manager/drivers/entity_handler.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  swagger/models.json
Labels: cla-not-required, run-e2e

#544 Fix Secrets UUID in get/list results
  pkg/secret-store/builder/dispatch_secret_builder.go
Labels: cla-not-required, run-e2e

#537 Add follow and last flags to get runs
  CHANGELOG.md
  pkg/client/functions.go
  pkg/client/mocks/functions_client.go
  pkg/dispatchcli/cmd/get_run.go
  pkg/function-manager/controller.go
  pkg/function-manager/controller_test.go
  pkg/function-manager/gen/client/runner/get_run_parameters.go
  pkg/function-manager/gen/client/runner/get_runs_parameters.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/operations/runner/get_run_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/get_run_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/runner/get_runs_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/get_runs_urlbuilder.go
  pkg/function-manager/handlers.go
  pkg/function-manager/handlers_test.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e
