Repository vmware/dispatch, pull requests merged in 2018-11, with the labels that each got.

#706 Update solo pipeline to notify slack of e2e failures
  ci/pipelines/e2e.yml
Labels: cla-not-required, run-e2e-solo

#710 change disk controller in ova
  scripts/ova/bootable/build-main.sh
  scripts/ova/bootable/config/builder.ovf
  scripts/ova/scripts/systemd/units/dispatch-server.service
  scripts/ova/scripts/systemd/units/repartition.service
  scripts/ova/scripts/systemd/units/storage-data.mount
  scripts/ova/scripts/systemd/units/storage-db.mount
  scripts/ova/scripts/systemd/units/storage-log.mount
Labels: cla-not-required

#712 Automate communication and auth for docker-based event drivers
  ci/e2e/run-tests.yml
  e2e/tests/events.bats
  e2e/tests/helpers.bash
  e2e/tests/variables.bash
  examples/event-drivers/go/ticker-driver/Gopkg.lock
  examples/event-drivers/go/ticker-driver/driver.go
  examples/event-drivers/go/ticker-driver/vendor/github.com/vmware/dispatch/pkg/events/driverclient/client.go
  examples/event-drivers/go/ticker-driver/vendor/github.com/vmware/dispatch/pkg/events/driverclient/http.go
  examples/event-drivers/go/ticker-driver/vendor/github.com/vmware/dispatch/pkg/utils/resource_names.go
  pkg/dispatchserver/main.go
  pkg/event-manager/drivers/docker_backend.go
  pkg/event-manager/gen/client/events/events_client.go
  pkg/event-manager/gen/client/events/ingest_event_parameters.go
  pkg/event-manager/gen/client/events/ingest_event_responses.go
  pkg/event-manager/gen/restapi/configure_event_manager.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/gen/restapi/operations/event_manager_api.go
  pkg/event-manager/gen/restapi/operations/events/ingest_event.go
  pkg/event-manager/gen/restapi/operations/events/ingest_event_parameters.go
  pkg/event-manager/gen/restapi/operations/events/ingest_event_responses.go
  pkg/event-manager/gen/restapi/operations/events/ingest_event_urlbuilder.go
  pkg/event-manager/handlers.go
  pkg/events/driverclient/client.go
  pkg/events/driverclient/http.go
  swagger/event-manager.yaml
Labels: cla-not-required, run-e2e-solo

#714 Update images.bats `Create with URL` test to use solo branch
  e2e/tests/images.bats
  examples/seed.yaml
  pkg/dispatchserver/main.go
Labels: cla-not-required

#695 drivereventtype expose
  pkg/dispatchcli/cmd/get_eventdriver.go
  pkg/event-manager/drivers/docker_backend.go
  pkg/event-manager/drivers/entity_handler.go
  pkg/event-manager/drivers/entity_handler_test.go
Labels: cla-not-required, run-e2e-solo

#713 add dispatch CLI to the OVA
  Makefile
  examples/event-drivers/go/ticker-driver/driver.go
  examples/event-drivers/go/ticker-driver/vendor/github.com/vmware/dispatch/pkg/events/driverclient/http.go
  ova/configs/config.json
  ova/ova-manifest.json
  ova/scripts/systemd/scripts/ova-firewall.sh
  ova/scripts/systemd/units/dispatch-server.service
  pkg/dispatchserver/main.go
  pkg/event-manager/drivers/docker_backend.go
  pkg/events/driverclient/http.go
Labels: cla-not-required

#709 Add hostname when list api endpoint
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/get_api.go
  pkg/dispatchserver/main.go
  pkg/utils/constants.go
Labels: cla-not-required

#716 change events gateway flag in e2e
  ci/e2e/run-tests.yml
Labels: cla-not-required, run-e2e-solo

#718 Add OVA build automation
  ci/configs/dispatch-config-local.json
  ci/configs/dispatch-install-local.yml
  ci/e2e/deploy-dispatch.yml
  ci/pipelines/e2e.yml
  ci/pipelines/ova-release.yml
  ci/pipelines/release.yml
  ci/release/binaries.yml
  ci/release/push-charts.sh
  ci/release/push-charts.yml
  ci/release/release-images.yml
  ci/tasks/binaries.yml
  ci/tasks/build-ova.yml
  ci/tasks/collect-logs.yml
  ci/tasks/prepare-version.yml
  ci/tasks/run-tests.yml
  ova/bootable/build-disks.sh
  ova/bootable/build-main.sh
  ova/build.sh
Labels: cla-not-required, run-e2e-solo

#723 add logo-only images
  docs/assets/images/dispatch-logo-only.png
  docs/assets/images/dispatch-logo-only.svg
Labels: cla-not-required

#719 Purge irrelevant docs from solo repo
  docs/_config.yml
  docs/_front/roadmap.md
  docs/_guides/building.md
  docs/_guides/docker-for-mac.md
  docs/_guides/eks.md
  docs/_guides/gke.md
  docs/_guides/minikube.md
  docs/_guides/quickstart.md
  docs/_guides/setup-authentication.md
  docs/_guides/setup-service-acccount-authentication.md
  docs/_guides/troubleshooting.md
  docs/_layouts/default.html
  docs/_layouts/post.html
  docs/_posts/2018-05-23-v0-1-15-release.md
  docs/_posts/2018-06-06-v0-1-16-release.md
  docs/_posts/2018-06-12-v0-1-17-release.md
  docs/_posts/2018-06-19-v0-1-18-release.md
  docs/_posts/2018-06-26-v0-1-19-release.md
  docs/_posts/2018-07-03-v0-1-20-release.md
  docs/_posts/2018-07-10-v0-1-21-release.md
  docs/_posts/2018-07-18-v0-1-22-release.md
  docs/_posts/2018-11-06-v0-1-24-release.md
  docs/_specs/application/application.md
  docs/_specs/functions.md
  docs/_usage/iam.md
  docs/_usage/services.md
  docs/assets/images/console.png
  docs/assets/images/fusion.png
Labels: cla-not-required

#725 Add Dispatch Solo OVA release pipeline
  Makefile
  ci/pipelines/ova-release.yml
  ci/tasks/binaries.yml
  ci/tasks/build-ova.yml
  ci/tasks/prepare-version.yml
  e2e/tests/apis.bats
Labels: Solo, cla-not-required, run-e2e-solo

#727 Copy dispatch ui to release ova
  ci/pipelines/ova-release.yml
  ci/tasks/build-ova.yml
  ova/ova-manifest.json
Labels: cla-not-required

#737 [Solo] get runs sort by
  pkg/dispatchcli/cmd/get_run.go
Labels: cla-not-required, run-e2e-solo

#745 Switch Toolbox to Open VM Tools
  Makefile
  cmd/toolbox/main.go
  ova/bootable/build-base.sh
  ova/ova-manifest.json
  ova/scripts/provisioners/system_settings.sh
  ova/scripts/systemd/units/toolbox.service
Labels: cla-not-required, run-e2e-solo

#750 [Solo] align storage
  ova/configs/server-config.yaml
  ova/configs/server-environment
  ova/ova-manifest.json
  ova/scripts/systemd/units/dispatch-server.service
  pkg/dispatchserver/main.go
Labels: Solo, cla-not-required, run-e2e-solo

#753 Update readme, examples and e2e for solo
  README.md
  docs/_examples/chat-ops.md
  docs/_examples/examples.md
  docs/assets/images/dispatch-solo-architecture.graffle
  docs/assets/images/dispatch-solo-architecture.png
  e2e/scripts/run-e2e.sh
  e2e/tests/apis.bats
  e2e/tests/variables.bash
Labels: cla-not-required, run-e2e-solo

#756 Add/update a redirect to the latest OVA
  ci/pipelines/ova-release.yml
  ci/s3/index.html
  ci/s3/redirect.json
  ci/tasks/update-release-redirect.yml
Labels: cla-not-required

#759 make OVA publicly accessible and fix tag
  ci/tasks/update-release-redirect.yml
  docs/_front/quickstart.md
  docs/_layouts/home.html
Labels: cla-not-required

#749 Add api gateway https port in quick start
  docs/_front/quickstart.md
  ova/configs/config.json
Labels: cla-not-required

#758 Fix fetching g/w https port in CLI
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/get_api.go
Labels: cla-not-required

#761 Fix dashes in g/w port
  docs/_front/quickstart.md
  ova/configs/config.json
Labels: cla-not-required

#763 Hello World Examples
  docs/_examples/hello-world.md
  docs/_front/quickstart.md
Labels: cla-not-required

#765 update examples
  docs/_examples/examples.md
Labels: cla-not-required

#764 Polish the Getting Started page
  docs/_front/quickstart.md
Labels: cla-not-required

#766 Fix Doc Links
  docs/_examples/examples.md
  docs/_examples/hello-world.md
Labels: cla-not-required

#767 One last doc fix
  docs/_examples/examples.md
Labels: cla-not-required

#762 Workaround for ovfenv not working after a reboot
  ova/bootable/build-app.sh
  ova/scripts/systemd/scripts/dispatch-appliance-environment.sh
  ova/scripts/systemd/scripts/network-config.sh
  ova/scripts/systemd/scripts/ovfenv_wrapper.sh
  ova/scripts/systemd/scripts/sshd_permitrootlogin.sh
Labels: cla-not-required, run-e2e-solo

#744 Add solo bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla-not-required

#771 Remove unused packages/binaries
  ova/bootable/build-base.sh
  ova/ova-manifest.json
  ova/scripts/provisioners/package_provisioning.sh
  ova/scripts/provisioners/provision_govc.sh
  ova/scripts/systemd/scripts/dispatch-appliance-tls.sh
Labels: cla-not-required, run-e2e-solo

#773 update homepage and overview
  docs/_front/overview.md
  docs/_layouts/home.html
  docs/index.md
Labels: cla-not-required

#774 Add vcenter events guide
  docs/_config.yml
  docs/_examples/vcenter-events.md
  docs/_posts/2018-11-06-v0-1-24-release.md
  docs/assets/images/harden-options.png
  pkg/dispatchserver/main.go
Labels: cla-not-required

#777 Use UnixNano for run's executed and finished time
  ci/pipelines/ova-release.yml
  pkg/dispatchcli/cmd/get_run.go
  pkg/function-manager/handlers.go
Labels: cla-not-required, run-e2e-solo

#775 Update README to direct Solo users appropriately
  README.md
Labels: cla-not-required

#776 Update README to mention the OVA
  README.md
Labels: cla-not-required

#779 Set restart policy to always in function and event driver containers
  pkg/event-manager/drivers/docker_backend.go
  pkg/functions/docker/driver.go
Labels: cla-not-required, run-e2e-solo

#780 update event driver image links
  NOTICE
  docs/_guides/working-with-events.md
Labels: cla-not-required

#783 Fix redirect to latest ova
  ci/s3/redirect.json
Labels: cla-not-required
