Repository vmware/dispatch, pull requests merged in 2018-03, with the labels that each got.

#249 Use helpers from k8s api/errors to check errors from k8s API
  pkg/functions/riff/driver.go
Labels: cla-not-required, run-e2e

#253 Fix typos/grammar/missing comments/inconsistencies from event manager PR
  .github/ISSUE_TEMPLATE.md
  docs/_guides/custom-event-drivers.md
  docs/_guides/working-with-events.md
  docs/_specs/event-manager/event-manager.md
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/create_eventdrivertype.go
  pkg/dispatchcli/cmd/create_subscription.go
  pkg/dispatchcli/cmd/delete_eventdrivertype.go
  pkg/dispatchcli/cmd/emit.go
  pkg/dispatchcli/cmd/get_eventdrivertype.go
  pkg/dispatchcli/cmd/get_subscription.go
Labels: cla-not-required

#258 fix docs typos and twitter
  docs/_layouts/community.html
  docs/index.md
Labels: cla-not-required

#259 Fix golint issues
  pkg/client/client.go
  pkg/client/functions.go
  pkg/client/mocks/functions_client.go
  pkg/dispatchcli/cmd/update_baseimage.go
  pkg/event-manager/drivers/mocks/backend.go
  pkg/event-sidecar/listener/pipe.go
  pkg/events/mocks/stream_parser.go
  pkg/events/mocks/subscription.go
  pkg/events/mocks/transport.go
  pkg/events/mocks/validator.go
  pkg/function-manager/doc.go
  pkg/function-manager/mocks/image_manager.go
  pkg/functions/builder.go
  pkg/functions/context.go
  pkg/functions/doc.go
  pkg/functions/mocks/ClientTransport.go
  pkg/functions/mocks/SecretInjector.go
  pkg/functions/mocks/faa_s_driver.go
  pkg/functions/mocks/image_builder.go
  pkg/functions/mocks/validator.go
  pkg/functions/noop/driver.go
  pkg/functions/openfaas/driver.go
  pkg/functions/openwhisk/driver.go
  pkg/functions/riff/driver.go
  pkg/functions/runner/runner.go
  pkg/functions/secretinjector/secretinjector.go
  pkg/functions/validator/noop.go
  pkg/functions/validator/validator.go
Labels: cla-not-required

#260 Fix golint issues
  pkg/entity-store/libkv.go
  pkg/identity-manager/casbin_entity_adapter.go
  pkg/identity-manager/entities.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/mocks/casbin_adapter_mock.go
  pkg/images/builder.go
  pkg/secret-store/builder/k8s_secret_builder.go
  pkg/secret-store/builder/vmw_secret_builder.go
  pkg/secret-store/entities.go
  pkg/secret-store/mocks/entity_store.go
  pkg/secret-store/mocks/secret_interface.go
  pkg/secret-store/service/k8s_secrets_service.go
  pkg/secret-store/service/k8s_secrets_service_test.go
  pkg/secret-store/service/secrets_service.go
  pkg/utils/backoff.go
  pkg/utils/tracing.go
Labels: cla-not-required

#262 Initial documentation for configuring policies
  docs/_guides/setup-authentication.md
Labels: cla-not-required

#230 Add tracking test coverage to Dashboard
  ci/pipelines/pull-requests.yml
  ci/units/coverage.yml
  scripts/coverage.sh
  scripts/parse_coverage_report.py
Labels: cla-not-required

#263 Appropriate error when creating an entity with non-unique name
  e2e/tests-riff/functions.bats
  e2e/tests/functions.bats
  pkg/dispatchcli/cmd/errors.go
  pkg/entity-store/libkv.go
  pkg/entity-store/postgres.go
  pkg/entity-store/store.go
  pkg/function-manager/gen/client/store/add_function_responses.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/operations/store/add_function_responses.go
  pkg/function-manager/handlers.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#272 update release pipeline for functions with templates
  ci/pipelines/release.yml
  ci/release/release-images.yml
Labels: cla-not-required

#277 remove k8s setup from push charts
  ci/release/push-charts.yml
Labels: cla-not-required

#276 Return 409 Conflict on non-unique names
  pkg/api-manager/gen/client/endpoint/add_api_responses.go
  pkg/api-manager/gen/restapi/embedded_spec.go
  pkg/api-manager/gen/restapi/operations/endpoint/add_api_responses.go
  pkg/api-manager/handlers.go
  pkg/application-manager/gen/client/application/add_app_responses.go
  pkg/application-manager/gen/restapi/embedded_spec.go
  pkg/application-manager/gen/restapi/operations/application/add_app_responses.go
  pkg/application-manager/handlers.go
  pkg/dispatchcli/cmd/errors.go
  pkg/event-manager/drivers/http_handlers.go
  pkg/event-manager/gen/client/drivers/add_driver_responses.go
  pkg/event-manager/gen/client/drivers/add_driver_type_responses.go
  pkg/event-manager/gen/client/subscriptions/add_subscription_responses.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/event-manager/gen/restapi/operations/drivers/add_driver_responses.go
  pkg/event-manager/gen/restapi/operations/drivers/add_driver_type_responses.go
  pkg/event-manager/gen/restapi/operations/subscriptions/add_subscription_responses.go
  pkg/event-manager/subscriptions/http_handlers.go
  pkg/image-manager/gen/client/base_image/add_base_image_responses.go
  pkg/image-manager/gen/client/image/add_image_responses.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/operations/base_image/add_base_image_responses.go
  pkg/image-manager/gen/restapi/operations/image/add_image_responses.go
  pkg/image-manager/handlers.go
  pkg/secret-store/gen/client/secret/add_secret_responses.go
  pkg/secret-store/gen/restapi/embedded_spec.go
  pkg/secret-store/gen/restapi/operations/secret/add_secret_responses.go
  pkg/secret-store/web/handlers.go
  swagger/api-manager.yaml
  swagger/application-manager.yaml
  swagger/event-manager.yaml
  swagger/image-manager.yaml
  swagger/secret-store.yaml
Labels: cla-not-required, run-e2e

#278 Return 409 for non-unique policy name
  pkg/identity-manager/gen/client/policy/add_policy_responses.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  pkg/identity-manager/gen/restapi/operations/policy/add_policy_responses.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
  swagger/identity-manager.yaml
Labels: cla-not-required

#279 batch of small fixes and docs
  docs/_guides/custom-event-drivers.md
  docs/_guides/setup-authentication.md
  docs/_layouts/post.html
  docs/_posts/2018-03-02-march-2018-release.md
  docs/assets/images/xueyang.jpg
  docs/assets/images/zimeng.jpg
  docs/community.md
  docs/news.md
  examples/python3/hello.py
Labels: cla-not-required

#280 remove missing chart from release and update image tag
  charts/dispatch/values.yaml
  ci/release/push-charts.sh
Labels: cla-not-required

#273 Add full API model support to create, update, delete by file
  e2e/tests-riff/images.yaml
  e2e/tests/images.yaml
  examples/seed.yaml
  pkg/api-manager/gen/models/api.go
  pkg/api-manager/gen/restapi/embedded_spec.go
  pkg/api-manager/handlers.go
  pkg/application-manager/gen/models/application.go
  pkg/application-manager/gen/restapi/embedded_spec.go
  pkg/application-manager/handlers.go
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_function.go
  pkg/dispatchcli/cmd/create_image.go
  pkg/dispatchcli/cmd/create_secret.go
  pkg/dispatchcli/cmd/delete.go
  pkg/dispatchcli/cmd/delete_function.go
  pkg/dispatchcli/cmd/delete_image.go
  pkg/dispatchcli/cmd/delete_secret.go
  pkg/dispatchcli/cmd/update.go
  pkg/event-manager/gen/models/driver.go
  pkg/event-manager/gen/models/subscription.go
  pkg/event-manager/gen/restapi/embedded_spec.go
  pkg/events/cloudevent.go
  pkg/function-manager/gen/models/function.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/handlers.go
  pkg/image-manager/gen/models/base_image.go
  pkg/image-manager/gen/models/image.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/handlers.go
  pkg/secret-store/builder/dispatch_secret_builder.go
  pkg/secret-store/gen/models/secret.go
  pkg/secret-store/gen/restapi/embedded_spec.go
  pkg/secret-store/service/k8s_secrets_service.go
  pkg/utils/constants.go
  swagger/api-manager.yaml
  swagger/application-manager.yaml
  swagger/event-manager.yaml
  swagger/function-manager.yaml
  swagger/image-manager.yaml
  swagger/secret-store.yaml
Labels: cla-not-required, run-e2e

#283 Increase backoff timeout in test
  pkg/utils/backoff_test.go
Labels: cla-not-required

#275 Move base-image from v1/image/base to v1/baseimage
  charts/dispatch/charts/api-manager/values.yaml
  charts/dispatch/charts/application-manager/values.yaml
  charts/dispatch/charts/echo-server/values.yaml
  charts/dispatch/charts/event-manager/values.yaml
  charts/dispatch/charts/function-manager/values.yaml
  charts/dispatch/charts/identity-manager/values.yaml
  charts/dispatch/charts/image-manager/values.yaml
  charts/dispatch/charts/secret-store/values.yaml
  charts/dispatch/templates/_helpers.tpl
  docs/_guides/troubleshooting.md
  pkg/image-manager/gen/client/base_image/add_base_image_responses.go
  pkg/image-manager/gen/client/base_image/base_image_client.go
  pkg/image-manager/gen/client/base_image/delete_base_image_by_name_responses.go
  pkg/image-manager/gen/client/base_image/get_base_image_by_name_responses.go
  pkg/image-manager/gen/client/base_image/get_base_images_responses.go
  pkg/image-manager/gen/client/base_image/update_base_image_by_name_responses.go
  pkg/image-manager/gen/client/image/add_image_responses.go
  pkg/image-manager/gen/client/image/delete_image_by_name_responses.go
  pkg/image-manager/gen/client/image/get_image_by_name_responses.go
  pkg/image-manager/gen/client/image/get_images_responses.go
  pkg/image-manager/gen/client/image/image_client.go
  pkg/image-manager/gen/client/image/update_image_by_name_responses.go
  pkg/image-manager/gen/client/image_manager_client.go
  pkg/image-manager/gen/restapi/doc.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/operations/base_image/add_base_image.go
  pkg/image-manager/gen/restapi/operations/base_image/add_base_image_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/base_image/delete_base_image_by_name.go
  pkg/image-manager/gen/restapi/operations/base_image/delete_base_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/base_image/get_base_image_by_name.go
  pkg/image-manager/gen/restapi/operations/base_image/get_base_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/base_image/get_base_images.go
  pkg/image-manager/gen/restapi/operations/base_image/get_base_images_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/base_image/update_base_image_by_name.go
  pkg/image-manager/gen/restapi/operations/base_image/update_base_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image/add_image.go
  pkg/image-manager/gen/restapi/operations/image/add_image_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image/delete_image_by_name.go
  pkg/image-manager/gen/restapi/operations/image/delete_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image/get_image_by_name.go
  pkg/image-manager/gen/restapi/operations/image/get_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image/get_images.go
  pkg/image-manager/gen/restapi/operations/image/get_images_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image/update_image_by_name.go
  pkg/image-manager/gen/restapi/operations/image/update_image_by_name_urlbuilder.go
  pkg/image-manager/gen/restapi/operations/image_manager_api.go
  pkg/image-manager/handlers_test.go
  swagger/image-manager.yaml
Labels: cla-not-required, run-e2e

#284 Support single ns mode and better service selection during install
  ci/e2e/collect-logs.yml
  ci/e2e/run-tests.yml
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/uninstall.go
Labels: cla-not-required, run-e2e

#289 Add version command
  Makefile
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/version.go
  pkg/version/version.go
Labels: cla-not-required

#287 update all references to old image urls
  docs/_guides/quickstart.md
  examples/bingo/base-image/Dockerfile
  examples/blog/base-image/Dockerfile
  examples/python3/clonevm.py
  examples/python3/gettemplates.py
  examples/python3/getvms.py
  examples/python3/hello.py
  examples/vcenter/README.md
  pkg/dispatchcli/cmd/update_baseimage.go
  pkg/functions/openfaas/driver_test.go
  scripts/demo.sh
Labels: cla-not-required

#290 update twitter
  docs/_layouts/community.html
Labels: cla-not-required

#291 Fix Markdown formatting mistake
  docs/_guides/minikube.md
Labels: cla-not-required

#296 Create a simple web example
  examples/web/README.md
  examples/web/config.js
  examples/web/index.html
Labels: cla-not-required

#293 Add get API support for policy
  pkg/identity-manager/handlers.go
Labels: cla-not-required

#292 Adds create/delete/get CLI support for policy
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/create_policy.go
  pkg/dispatchcli/cmd/create_policy_test.go
  pkg/dispatchcli/cmd/delete.go
  pkg/dispatchcli/cmd/delete_policy.go
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/get.go
  pkg/dispatchcli/cmd/get_policy.go
  pkg/dispatchcli/cmd/rest_clients.go
  pkg/utils/constants.go
Labels: cla-not-required

#298 Update PowerShell base image & add powershell runtime dependency manager
  Makefile
  e2e/tests/functions.bats
  e2e/tests/images.bats
  e2e/tests/images.yaml
  e2e/tests/variables.bash
  examples/powershell/powercli-run-vm-script.ps1
  examples/powershell/requirements.psd1
  examples/powershell/test-slack.ps1
  examples/seed.yaml
  images/base-images/powershell/Dockerfile
  images/base-images/powershell/build.sh
  images/function-manager/templates/openfaas/powershell/Dockerfile
  images/function-manager/templates/openfaas/powershell/index.ps1
  pkg/image-manager/runtimes/nodejs6.go
  pkg/image-manager/runtimes/powershell.go
  pkg/image-manager/runtimes/powershell_test.go
  pkg/image-manager/runtimes/python2.go
  pkg/image-manager/runtimes/python3.go
Labels: run-e2e

#307 Batch resource creation file path to function definition and CLI output
  docs/_guides/quickstart.md
  examples/seed.yaml
  pkg/dispatchcli/cmd/create.go
Labels: cla-not-required

#305 Add update CLI/API support for Policy
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/get_policy.go
  pkg/dispatchcli/cmd/update.go
  pkg/dispatchcli/cmd/update_policy.go
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
  pkg/identity-manager/policy_handler_test.go
Labels: cla-not-required

#303 Fixes ambiguity in function manager handler names and REST API url conflict
  charts/dispatch/charts/function-manager/values.yaml
  pkg/client/functions.go
  pkg/dispatchcli/cmd/get_run.go
  pkg/function-manager/gen/client/function_manager_client.go
  pkg/function-manager/gen/client/runner/get_function_runs_responses.go
  pkg/function-manager/gen/client/runner/get_run_parameters.go
  pkg/function-manager/gen/client/runner/get_run_responses.go
  pkg/function-manager/gen/client/runner/get_runs_parameters.go
  pkg/function-manager/gen/client/runner/run_function_responses.go
  pkg/function-manager/gen/client/runner/runner_client.go
  pkg/function-manager/gen/client/store/add_function_responses.go
  pkg/function-manager/gen/client/store/delete_function_responses.go
  pkg/function-manager/gen/client/store/get_function_responses.go
  pkg/function-manager/gen/client/store/get_functions_responses.go
  pkg/function-manager/gen/client/store/store_client.go
  pkg/function-manager/gen/client/store/update_function_responses.go
  pkg/function-manager/gen/restapi/doc.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/operations/function_manager_api.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/runner/get_run.go
  pkg/function-manager/gen/restapi/operations/runner/get_run_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/get_run_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/runner/get_runs_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/get_runs_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/runner/run_function.go
  pkg/function-manager/gen/restapi/operations/runner/run_function_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/store/add_function.go
  pkg/function-manager/gen/restapi/operations/store/add_function_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/store/delete_function.go
  pkg/function-manager/gen/restapi/operations/store/delete_function_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/store/get_function.go
  pkg/function-manager/gen/restapi/operations/store/get_function_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/store/get_functions.go
  pkg/function-manager/gen/restapi/operations/store/get_functions_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/store/update_function.go
  pkg/function-manager/gen/restapi/operations/store/update_function_urlbuilder.go
  pkg/function-manager/handlers.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#314 Update GKE cluster version in CI
  ci/e2e/gke-cluster-create.yml
Labels: cla-not-required, run-e2e

#316 Set the binaries version in CI release pipeline
  Makefile
  ci/pipelines/release.yml
  ci/release/binaries.yml
Labels: cla-not-required

#317 Fix documentation to point to latest release
  docs/_guides/quickstart.md
Labels: cla-not-required

#318 Fix release pipeline
  charts/dispatch/Chart.yaml
  ci/pipelines/e2e.yml
  ci/pipelines/pull-requests.yml
  ci/pipelines/release.yml
  ci/release/push-charts.yml
Labels: cla-not-required, run-e2e

#312 initial service catalog spec
  docs/_specs/service-manager/service-manager.md
Labels: cla-not-required

#285 Cleanup leftover resources after deleting a cluster on GKE
  ci/e2e/cleanup.yml
Labels: cla-not-required, run-e2e

#321 Add GKE cleanup script
  scripts/gke-cleanup.sh
Labels: cla-not-required

#323 Update auth for bootstrap user/mode
  charts/dispatch/charts/identity-manager/templates/secret.yaml
  pkg/identity-manager/handlers.go
  pkg/identity-manager/handlers_test.go
Labels: cla-not-required

#324 Enable golint checks in ci
  Makefile
  ci/units/check-syntax.yml
  pkg/entity-store/store.go
  pkg/functions/context.go
  pkg/functions/riff/requester.go
  pkg/utils/close.go
  scripts/golintcheck.sh
Labels: cla-not-required

#313 Removed path /function/{functionName}/runs
  charts/kong/dispatch-transformer/handler.lua
  charts/kong/dispatch-transformer/schema.lua
  pkg/api-manager/gateway/kong/kong.go
  pkg/client/functions.go
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/exec.go
  pkg/dispatchcli/cmd/get_run.go
  pkg/function-manager/gen/client/runner/get_function_runs_parameters.go
  pkg/function-manager/gen/client/runner/get_function_runs_responses.go
  pkg/function-manager/gen/client/runner/get_runs_parameters.go
  pkg/function-manager/gen/client/runner/run_function_parameters.go
  pkg/function-manager/gen/client/runner/run_function_responses.go
  pkg/function-manager/gen/client/runner/runner_client.go
  pkg/function-manager/gen/restapi/configure_function_manager.go
  pkg/function-manager/gen/restapi/embedded_spec.go
  pkg/function-manager/gen/restapi/operations/function_manager_api.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs_responses.go
  pkg/function-manager/gen/restapi/operations/runner/get_function_runs_urlbuilder.go
  pkg/function-manager/gen/restapi/operations/runner/get_runs_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/run_function.go
  pkg/function-manager/gen/restapi/operations/runner/run_function_parameters.go
  pkg/function-manager/gen/restapi/operations/runner/run_function_urlbuilder.go
  pkg/function-manager/handlers.go
  pkg/function-manager/handlers_test.go
  swagger/function-manager.yaml
Labels: cla-not-required, run-e2e

#325 Topic/ntenczar/cli update image
  docs/_guides/quickstart.md
  examples/seed.yaml
  pkg/dispatchcli/cmd/create.go
  pkg/dispatchcli/cmd/errors.go
  pkg/dispatchcli/cmd/update.go
  pkg/dispatchcli/cmd/update_image.go
  pkg/event-manager/drivers/entities/driver.go
  pkg/image-manager/entities.go
  pkg/image-manager/gen/client/image/update_image_by_name_responses.go
  pkg/image-manager/gen/models/runtime_dependencies.go
  pkg/image-manager/gen/models/status.go
  pkg/image-manager/gen/restapi/embedded_spec.go
  pkg/image-manager/gen/restapi/operations/image/update_image_by_name_responses.go
  pkg/image-manager/handlers.go
  pkg/image-manager/handlers_test.go
  swagger/image-manager.yaml
Labels: cla-not-required

#331 Fix for getting deployment objects in K8S 1.7
  pkg/functions/openfaas/driver.go
Labels: cla-not-required, run-e2e

#330 Support for additional chart options and single ns uninstall
  pkg/dispatchcli/cmd/cmd.go
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/dispatchcli/cmd/uninstall.go
Labels: cla-not-required, run-e2e

#334 Fix swagger definition for policy rules
  pkg/identity-manager/gen/models/rule.go
  pkg/identity-manager/gen/restapi/embedded_spec.go
  swagger/identity-manager.yaml
Labels: cla-not-required

#336 Update docs and add art
  README.md
  docs/_specs/development.md
  docs/assets/images/120500-vmw-os-lgo-dispatch-final.eps
  docs/assets/images/logo-large.png
  docs/assets/images/nick.jpg
  docs/assets/images/russell.jpg
  docs/community.md
Labels: cla-not-required

#335 Policy CLI improvement: add `--wide` option to display rule content and format rule output
  pkg/dispatchcli/cmd/get_policy.go
Labels: cla-not-required

#340 Reduce unit tests CI job chatiness
  ci/pipelines/pull-requests.yml
  ci/units/check-headers.yml
  ci/units/check-tests.yml
  ci/units/swagger-generate.yml
  ci/units/unit-tests.yml
  scripts/generate.sh
  scripts/header-check.sh
  scripts/test-check.sh
Labels: cla-not-required

#343 Make RabbitMQ chart configurable
  charts/dispatch/charts/event-manager/templates/deployment.yaml
  charts/dispatch/requirements.lock
  charts/dispatch/requirements.yaml
  charts/dispatch/values.yaml
  pkg/dispatchcli/cmd/install.go
  pkg/dispatchcli/cmd/install_config.go
  pkg/dispatchcli/cmd/uninstall.go
Labels: cla-not-required, run-e2e

#326 API gateway form encoding support
  charts/kong/dispatch-transformer/handler.lua
  e2e/tests/apis.bats
Labels: cla-not-required, run-e2e

#345 Updated blog and bingo examples to use image run-time dependencies
  examples/bingo/README.md
  examples/bingo/base-image/Dockerfile
  examples/bingo/package.json
  examples/blog/README.md
  examples/blog/base-image/Dockerfile
  examples/blog/package.json
Labels: cla-not-required
